DO $$
    BEGIN
        -- Check if the 'users' table exists
        IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'users' AND schemaname = 'public') THEN
            -- Create table if it does not exist

            CREATE TABLE users
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    username  VARCHAR(255)                            NOT NULL,
    email     VARCHAR(255)                            NOT NULL,
    device_id VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_device UNIQUE (device_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

END IF;
END $$;
