DO $$
    BEGIN
        -- Check if the 'users' table exists
        IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE tablename = 'roles' AND schemaname = 'public') THEN
            -- Create table if it does not exist

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

        END IF;
    END $$;