ALTER TABLE rooms
    ALTER COLUMN host_id DROP NOT NULL;

ALTER TABLE rooms
    ALTER COLUMN is_active DROP NOT NULL;

ALTER TABLE rooms
    ALTER COLUMN is_private DROP NOT NULL;

ALTER TABLE rooms
    ALTER COLUMN name DROP NOT NULL;

ALTER TABLE rooms
    ALTER COLUMN slug DROP NOT NULL;