CREATE TABLE votes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    score       INTEGER,
    status      VARCHAR(255),
    room_id     UUID,
    question_id UUID,
    user_id     BIGINT,
    CONSTRAINT pk_votes PRIMARY KEY (id)
);

ALTER TABLE votes
    ADD CONSTRAINT FK_VOTES_ON_QUESTION FOREIGN KEY (question_id) REFERENCES questions (id);

ALTER TABLE votes
    ADD CONSTRAINT FK_VOTES_ON_ROOM FOREIGN KEY (room_id) REFERENCES rooms (id);

ALTER TABLE votes
    ADD CONSTRAINT FK_VOTES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);