version: "3.7"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=goscrum_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    image: amazoncorretto:17
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ./gradlew bootRun -Dspring_profiles_active=docker
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
